/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DuetDatePickerChangeEvent, DuetDatePickerDirection, DuetDatePickerFocusEvent } from "./components/duet-date-picker/duet-date-picker";
import { DaysOfWeek } from "./components/duet-date-picker/date-utils";
import { DuetLocalizedText } from "./components/duet-date-picker/date-localization";
import { DuetDateAdapter } from "./components/duet-date-picker/date-adapter";
import { VaccineApplication } from "./components/data-service/models";
export namespace Components {
    interface AlertDialog {
        "language": string;
        "message": string;
    }
    interface AutoComplete {
        "environment": string;
        "filterKey": string;
        "language": string;
        "placeholder": string;
        "token_api_nimbo": string;
    }
    interface DuetDatePicker {
        /**
          * Date adapter, for custom parsing/formatting. Must be object with a `parse` function which accepts a `string` and returns a `Date`, and a `format` function which accepts a `Date` and returns a `string`. Default is IS0-8601 parsing and formatting.
         */
        "dateAdapter": DuetDateAdapter;
        /**
          * Forces the opening direction of the calendar modal to be always left or right. This setting can be useful when the input is smaller than the opening date picker would be as by default the picker always opens towards right.
         */
        "direction": DuetDatePickerDirection;
        /**
          * Makes the date picker input component disabled. This prevents users from being able to interact with the input, and conveys its inactive state to assistive technologies.
         */
        "disabled": boolean;
        /**
          * Which day is considered first day of the week? `0` for Sunday, `1` for Monday, etc. Default is Monday.
         */
        "firstDayOfWeek": DaysOfWeek;
        /**
          * Hide the calendar modal. Set `moveFocusToButton` to false to prevent focus returning to the date picker's button. Default is true.
         */
        "hide": (moveFocusToButton?: boolean) => Promise<void>;
        /**
          * Adds a unique identifier for the date picker input. Use this instead of html `id` attribute.
         */
        "identifier": string;
        /**
          * Button labels, day names, month names, etc, used for localization. Default is English.
         */
        "localization": DuetLocalizedText;
        /**
          * Maximum date allowed to be picked. Must be in IS0-8601 format: YYYY-MM-DD. This setting can be used alone or together with the min property.
         */
        "max": string;
        /**
          * Minimum date allowed to be picked. Must be in IS0-8601 format: YYYY-MM-DD. This setting can be used alone or together with the max property.
         */
        "min": string;
        /**
          * Name of the date picker input.
         */
        "name": string;
        /**
          * Should the input be marked as required?
         */
        "required": boolean;
        /**
          * Defines a specific role attribute for the date picker input.
         */
        "role": string;
        /**
          * Sets focus on the date picker's input. Use this method instead of the global `focus()`.
         */
        "setFocus": () => Promise<void>;
        /**
          * Show the calendar modal, moving focus to the calendar inside.
         */
        "show": () => Promise<void>;
        /**
          * Date value. Must be in IS0-8601 format: YYYY-MM-DD.
         */
        "value": string;
    }
    interface ModalDialog {
        "language": string;
        "showModal": boolean;
    }
    interface VaccinationCard {
        "environment": string;
        "language": string;
        "person_id": number;
        "token_api_nimbo": string;
        "vaccines": VaccineApplication[];
    }
    interface VaccinationModule {
        "environment": string;
        "language": string;
        "person_id": number;
        "token_api_nimbo": string;
    }
    interface VaccineTable {
        "environment": string;
        "language": string;
        "token_api_nimbo": string;
        "vaccines": VaccineApplication[];
    }
}
declare global {
    interface HTMLAlertDialogElement extends Components.AlertDialog, HTMLStencilElement {
    }
    var HTMLAlertDialogElement: {
        prototype: HTMLAlertDialogElement;
        new (): HTMLAlertDialogElement;
    };
    interface HTMLAutoCompleteElement extends Components.AutoComplete, HTMLStencilElement {
    }
    var HTMLAutoCompleteElement: {
        prototype: HTMLAutoCompleteElement;
        new (): HTMLAutoCompleteElement;
    };
    interface HTMLDuetDatePickerElement extends Components.DuetDatePicker, HTMLStencilElement {
    }
    var HTMLDuetDatePickerElement: {
        prototype: HTMLDuetDatePickerElement;
        new (): HTMLDuetDatePickerElement;
    };
    interface HTMLModalDialogElement extends Components.ModalDialog, HTMLStencilElement {
    }
    var HTMLModalDialogElement: {
        prototype: HTMLModalDialogElement;
        new (): HTMLModalDialogElement;
    };
    interface HTMLVaccinationCardElement extends Components.VaccinationCard, HTMLStencilElement {
    }
    var HTMLVaccinationCardElement: {
        prototype: HTMLVaccinationCardElement;
        new (): HTMLVaccinationCardElement;
    };
    interface HTMLVaccinationModuleElement extends Components.VaccinationModule, HTMLStencilElement {
    }
    var HTMLVaccinationModuleElement: {
        prototype: HTMLVaccinationModuleElement;
        new (): HTMLVaccinationModuleElement;
    };
    interface HTMLVaccineTableElement extends Components.VaccineTable, HTMLStencilElement {
    }
    var HTMLVaccineTableElement: {
        prototype: HTMLVaccineTableElement;
        new (): HTMLVaccineTableElement;
    };
    interface HTMLElementTagNameMap {
        "alert-dialog": HTMLAlertDialogElement;
        "auto-complete": HTMLAutoCompleteElement;
        "duet-date-picker": HTMLDuetDatePickerElement;
        "modal-dialog": HTMLModalDialogElement;
        "vaccination-card": HTMLVaccinationCardElement;
        "vaccination-module": HTMLVaccinationModuleElement;
        "vaccine-table": HTMLVaccineTableElement;
    }
}
declare namespace LocalJSX {
    interface AlertDialog {
        "language"?: string;
        "message"?: string;
    }
    interface AutoComplete {
        "environment"?: string;
        "filterKey"?: string;
        "language"?: string;
        "onItemSelected"?: (event: CustomEvent<any>) => void;
        "onItemSelectedAddManually"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "token_api_nimbo"?: string;
    }
    interface DuetDatePicker {
        /**
          * Date adapter, for custom parsing/formatting. Must be object with a `parse` function which accepts a `string` and returns a `Date`, and a `format` function which accepts a `Date` and returns a `string`. Default is IS0-8601 parsing and formatting.
         */
        "dateAdapter"?: DuetDateAdapter;
        /**
          * Forces the opening direction of the calendar modal to be always left or right. This setting can be useful when the input is smaller than the opening date picker would be as by default the picker always opens towards right.
         */
        "direction"?: DuetDatePickerDirection;
        /**
          * Makes the date picker input component disabled. This prevents users from being able to interact with the input, and conveys its inactive state to assistive technologies.
         */
        "disabled"?: boolean;
        /**
          * Which day is considered first day of the week? `0` for Sunday, `1` for Monday, etc. Default is Monday.
         */
        "firstDayOfWeek"?: DaysOfWeek;
        /**
          * Adds a unique identifier for the date picker input. Use this instead of html `id` attribute.
         */
        "identifier"?: string;
        /**
          * Button labels, day names, month names, etc, used for localization. Default is English.
         */
        "localization"?: DuetLocalizedText;
        /**
          * Maximum date allowed to be picked. Must be in IS0-8601 format: YYYY-MM-DD. This setting can be used alone or together with the min property.
         */
        "max"?: string;
        /**
          * Minimum date allowed to be picked. Must be in IS0-8601 format: YYYY-MM-DD. This setting can be used alone or together with the max property.
         */
        "min"?: string;
        /**
          * Name of the date picker input.
         */
        "name"?: string;
        /**
          * Event emitted the date picker input is blurred.
         */
        "onDuetBlur"?: (event: CustomEvent<DuetDatePickerFocusEvent>) => void;
        /**
          * Event emitted when a date is selected.
         */
        "onDuetChange"?: (event: CustomEvent<DuetDatePickerChangeEvent>) => void;
        /**
          * Event emitted the date picker input is focused.
         */
        "onDuetFocus"?: (event: CustomEvent<DuetDatePickerFocusEvent>) => void;
        /**
          * Should the input be marked as required?
         */
        "required"?: boolean;
        /**
          * Defines a specific role attribute for the date picker input.
         */
        "role"?: string;
        /**
          * Date value. Must be in IS0-8601 format: YYYY-MM-DD.
         */
        "value"?: string;
    }
    interface ModalDialog {
        "language"?: string;
        "onConfirmationDelete"?: (event: CustomEvent<any>) => void;
        "showModal"?: boolean;
    }
    interface VaccinationCard {
        "environment"?: string;
        "language"?: string;
        "onVaccineDeleted"?: (event: CustomEvent<any>) => void;
        "person_id"?: number;
        "token_api_nimbo"?: string;
        "vaccines"?: VaccineApplication[];
    }
    interface VaccinationModule {
        "environment"?: string;
        "language"?: string;
        "person_id"?: number;
        "token_api_nimbo"?: string;
    }
    interface VaccineTable {
        "environment"?: string;
        "language"?: string;
        "onVaccineDeleted"?: (event: CustomEvent<any>) => void;
        "onVaccineEdit"?: (event: CustomEvent<any>) => void;
        "onVaccineSave"?: (event: CustomEvent<any>) => void;
        "token_api_nimbo"?: string;
        "vaccines"?: VaccineApplication[];
    }
    interface IntrinsicElements {
        "alert-dialog": AlertDialog;
        "auto-complete": AutoComplete;
        "duet-date-picker": DuetDatePicker;
        "modal-dialog": ModalDialog;
        "vaccination-card": VaccinationCard;
        "vaccination-module": VaccinationModule;
        "vaccine-table": VaccineTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "alert-dialog": LocalJSX.AlertDialog & JSXBase.HTMLAttributes<HTMLAlertDialogElement>;
            "auto-complete": LocalJSX.AutoComplete & JSXBase.HTMLAttributes<HTMLAutoCompleteElement>;
            "duet-date-picker": LocalJSX.DuetDatePicker & JSXBase.HTMLAttributes<HTMLDuetDatePickerElement>;
            "modal-dialog": LocalJSX.ModalDialog & JSXBase.HTMLAttributes<HTMLModalDialogElement>;
            "vaccination-card": LocalJSX.VaccinationCard & JSXBase.HTMLAttributes<HTMLVaccinationCardElement>;
            "vaccination-module": LocalJSX.VaccinationModule & JSXBase.HTMLAttributes<HTMLVaccinationModuleElement>;
            "vaccine-table": LocalJSX.VaccineTable & JSXBase.HTMLAttributes<HTMLVaccineTableElement>;
        }
    }
}
